# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gidhub
brief-intro: BE Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# url에 임의의 값을 넣으면
# {{site.url}} 사용시 local 환경에서도 지정한 값을 사용한다.
    

permalink: /:title/

# other links
github_username:  goodGid
linkedIn_username: kiyong-shin-a498a2142
facebook_username: hello.goodgid
insta_username: ___gid
# email: hello.goodgid@gmail.com

description_footer: ""

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: goodGid

# Statistic Analysis 
google_analytics_id: UA-124748625-1 # google analytics id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir:         _sass
  style:            compressed

# port (default = 4000)
# port: 4000

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6

future: true
incremental: false
regenerate : true